var group___ocilib_c_api =
[
    [ "Character sets", "group___ocilib_c_api_supported_charsets.html", null ],
    [ "Data types", "group___ocilib_c_api_datatypes.html", "group___ocilib_c_api_datatypes" ],
    [ "Initializing the library", "group___ocilib_c_api_initialization.html", "group___ocilib_c_api_initialization" ],
    [ "Error handling", "group___ocilib_c_api_error_handling.html", "group___ocilib_c_api_error_handling" ],
    [ "Connecting to Database", "group___ocilib_c_api_connections.html", "group___ocilib_c_api_connections" ],
    [ "Oracle Pools", "group___ocilib_c_api_pools.html", "group___ocilib_c_api_pools" ],
    [ "Managing transactions", "group___ocilib_c_api_transactions.html", "group___ocilib_c_api_transactions" ],
    [ "Executing statements", "group___ocilib_c_api_statements.html", "group___ocilib_c_api_statements" ],
    [ "Binding variables and arrays", "group___ocilib_c_api_binding.html", "group___ocilib_c_api_binding" ],
    [ "Fetching data", "group___ocilib_c_api_fetching.html", "group___ocilib_c_api_fetching" ],
    [ "PL/SQL Support", "group___ocilib_c_api_pl_sql.html", "group___ocilib_c_api_pl_sql" ],
    [ "Oracle collections (VARRAYS and Nested Tables)", "group___ocilib_c_api_collections.html", "group___ocilib_c_api_collections" ],
    [ "Oracle Returning feature", "group___ocilib_c_api_feature_returning_into.html", "group___ocilib_c_api_feature_returning_into" ],
    [ "Oracle Rowids", "group___ocilib_c_api_row_ids.html", null ],
    [ "Statements control", "group___ocilib_c_api_statement_control.html", "group___ocilib_c_api_statement_control" ],
    [ "Internal Large Objects (LOBs)", "group___ocilib_c_api_lobs.html", "group___ocilib_c_api_lobs" ],
    [ "External Large Objects (FILEs)", "group___ocilib_c_api_files.html", "group___ocilib_c_api_files" ],
    [ "Long objects", "group___ocilib_c_api_longs.html", "group___ocilib_c_api_longs" ],
    [ "Date/time manipulation", "group___ocilib_c_api_datetimes.html", "group___ocilib_c_api_datetimes" ],
    [ "Timestamps and intervals manipulation", "group___ocilib_c_api_timestamps.html", "group___ocilib_c_api_timestamps" ],
    [ "Oracle Named Types (Oracle OBJECTs)", "group___ocilib_c_api_user_types.html", "group___ocilib_c_api_user_types" ],
    [ "Aborting long operations", "group___ocilib_c_api_abort.html", "group___ocilib_c_api_abort" ],
    [ "Describing Schema Meta data and Objects", "group___ocilib_c_api_metadata.html", "group___ocilib_c_api_metadata" ],
    [ "Formatted functions", "group___ocilib_c_api_formatting.html", "group___ocilib_c_api_formatting" ],
    [ "Hash tables", "group___ocilib_c_api_hash_tables.html", "group___ocilib_c_api_hash_tables" ],
    [ "Threads and mutexes", "group___ocilib_c_api_threading.html", "group___ocilib_c_api_threading" ],
    [ "Direct Path loading", "group___ocilib_c_apidirect_path.html", "group___ocilib_c_apidirect_path" ],
    [ "Oracle Advanced Queuing (A/Q)", "group___ocilib_c_api_advanced_queuing.html", "group___ocilib_c_api_advanced_queuing" ],
    [ "Database Change notifications (DCN or CQN)", "group___ocilib_c_api_subscriptions.html", "group___ocilib_c_api_subscriptions" ],
    [ "Remote Instance startup/shutdown", "group___ocilib_c_api_instances_management.html", "group___ocilib_c_api_instances_management" ],
    [ "Using OCI Handles directly", "group___ocilib_c_api_raw_handles.html", "group___ocilib_c_api_raw_handles" ],
    [ "OCILIB main demo application code", "group___ocilib_c_api_demo_application.html", null ]
];