OCILIB (C and C++ Driver for Oracle): ocilib::Long< T, U > Class Template Reference
ocilib::Long< T, U > Class Template Reference
Object identifying the SQL data type LONG.
#include <types.hpp>
Inherits ocilib::core::HandleHolder< OCI_Long * >.
Public Member Functions
Long ()
Create an empty null Long instance.
Long (const Statement &statement)
Constructor.
unsigned int Write (const T &content)
Write the given string into the long Object.
unsigned int GetLength () const
Return the buffer length.
T GetContent () const
Return the string read from a fetch sequence.
Detailed Description
template<class T, int U>
class ocilib::Long< T, U >
Object identifying the SQL data type LONG.
This class wraps the OCILIB object handle OCI_LONG of type OCI_CLONG and its related methods
Definition at line 202 of file config.hpp.
Constructor & Destructor Documentation
Long() [1/2]
template<class T , int U> ocilib::Long< T, U >::Long ()
Create an empty null Long instance.
Definition at line 29 of file Long.hpp.
Long() [2/2]
template<class T , int U> ocilib::Long< T, U >::Long (const Statement & statement)
Constructor.
Parameters
statement - statement object that will handle operations on the long buffer
Definition at line 34 of file Long.hpp.
References ocilib::core::Check(), OCI_LongCreate(), and OCI_LongFree().
Member Function Documentation
Write()
template<class T , int U> unsigned int ocilib::Long< T, U >::Write (const T & content)
Write the given string into the long Object.
Parameters
content - string to write
Returns
Number of character written
Definition at line 46 of file Long.hpp.
References ocilib::core::Check(), and OCI_LongWrite().
GetLength()
template<class T , int U> unsigned int ocilib::Long< T, U >::GetLength () const
Return the buffer length.
Definition at line 57 of file Long.hpp.
References ocilib::core::Check(), and OCI_LongGetSize().
GetContent()
template<class T , int U> T ocilib::Long< T, U >::GetContent () const
Return the string read from a fetch sequence.